# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: d5866b9
_src_path: git+https://git.sr.ht/~nicoco/slidge-template
author: deuill
author_email: alex@deuill.org
author_website: https://deuill.org
dockerhub_username: nicocool84
legacy_lib: whatsmeow
legacy_lib_website: https://github.com/tulir/whatsmeow
legacy_service: WhatsApp
legacy_service_website: https://whatsapp.com
module_name: slidge_whatsapp
project_name: slidge-whatsapp
python_version: '3.9'
srht_secret_c3p0: dc710d9d-8043-4e1d-9837-b35bfa02800a
srht_secret_docker: 173244e1-c233-43de-969f-65965c5487e1
srht_secret_pypi: 3ecea679-dec7-4ac0-8821-75d0f4fe0773
srht_username: nicoco
xeps:
-   note: Groups are supported, including administration, moderation and creation.
    number: 45
    status: complete
-   note: Typing notifications only.
    number: 85
    status: complete
-   note: WhatApp has proper recipient-generated delivery receipts, and slidge supports
        them.
    number: 184
    status: complete
-   note: Only available if you chose to share your presence info in the official
        WhatsApp client.
    number: 319
    status: complete
-   note: Sending and receiving message edits is only supported in the latest versions
        of the official WhatsApp clients.
    number: 308
    status: complete
-   note: Displayed and received markers are supported. In groups, you only get markers
        for messages you have sent, just like in official WhatsApp clients.
    number: 333
    status: complete
-   note: null
    number: 363
    status: complete
-   note: null
    number: 424
    status: complete
-   note: null
    number: 444
    status: complete
-   note: null
    number: 461
    status: complete
