stages:
  - sync

variables:
  SYNC_ONLY: "true"
  GIT_UPSTREAM_REPO_NAME: source-hut
  GIT_UPSTREAM_REPO_URL: https://git.sr.ht/~nicoco/slidge-whatsapp
  GIT_UPSTREAM_REPO_BRANCH: master
  GIT_SYNC_USER: git-sync
  GIT_SYNC_EMAIL: info@rimkus.it

.imgjob:
  image: docker
  services:
    - name: docker:dind
      command: ["--experimental"]
  variables:
    DOCKER_DRIVER: overlay2
    BUILDX_VERSION: v0.10.5
    BUILDX_ARCHITECTURE: linux-arm64
  tags:
    - docker
    - arm64
  before_script:
    - mkdir utils
    - apk add --no-cache make bash curl
    - mkdir -p ~/.docker/cli-plugins
    - curl -sSLo ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.$BUILDX_ARCHITECTURE
    - chmod +x ~/.docker/cli-plugins/docker-buildx

sync_upstream:
  stage: sync
  image: alpine
  tags:
    - docker
    - arm64
  before_script:
    - apk add git
    - git config --global user.name "${GIT_SYNC_USER}"
    - git config --global user.email "${GIT_SYNC_EMAIL}"
  script:
    - git remote remove "${GIT_UPSTREAM_REPO_NAME}"
    - git remote add "${GIT_UPSTREAM_REPO_NAME}" "${GIT_UPSTREAM_REPO_URL}"
    - git fetch "${GIT_UPSTREAM_REPO_NAME}" "${GIT_UPSTREAM_REPO_BRANCH}"
    - git merge "${GIT_UPSTREAM_REPO_NAME}/${GIT_UPSTREAM_REPO_BRANCH}"
    - git add .
    - git commit -m "sync from upstream repo ${GIT_UPSTREAM_REPO_URL}"
    - git push origin
  when: manual
  rules:
    - if: $SYNC_ONLY == 'true'
      when: always
