version: "3.9"
services:
  slidge:
    build:
      context: .
      target: slidge-whatsapp-dev
    command:
     - --jid=slidge.localhost
     - --secret=secret
     - --upload-service=upload.localhost
     - --debug
    network_mode: service:prosody
    volumes:
      - ../slidge/slidge:/venv/lib/python/site-packages/slidge
      - ./slidge_whatsapp:/venv/lib/python/site-packages/slidge_whatsapp
      - ./persistent:/var/lib/slidge
    depends_on:
      prosody:
        condition: service_started
    environment:
      SLIDGE_WA_ATTACHMENTS_ON_DISK: "1"

  prosody:
    image: docker.io/nicocool84/slidge-prosody-dev:latest
    ports:
      - "127.0.0.1:5281:5281" # XMPP port for clients to connect to
      - "127.0.0.1:5222:5222" # prosody's http_file_share
      - "127.0.0.1:4444:4444" # for nginx (optional, no-upload)
      - "127.0.0.1:8888:80" # for movim (optional)
